packages:
  - 'packages/*'
  - 'packages/apps/*'
  - 'docs'
  - 'store'
  - 'store/*'
  - 'store/functions/*'
  - 'store/functions/ssr/storefront'
  - '.ecomplus/stores/*'
  - '.ecomplus/stores/*/*'
  - '.ecomplus/stores/*/functions/*'
  - '.ecomplus/stores/*/functions/ssr/storefront'
