name: Release please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
          monorepo-tags: true
          default-branch: develop

      - if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v3

      - if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - if: ${{ steps.release.outputs.releases_created }}
        run: npx zx ./scripts/publish.cjs
        env:
          RELEASE_PLEASE_OUTPUT: ${{ toJson(steps.release.outputs) }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
